---
title: "Practica 3"
format: revealjs
author: "Marcos Gibert y Javi Torres"
editor: visual
---

## Presentación
El dataset Boston Housing Dataset es un conjunto de datos sobre la ciudad de Boston en relación a las viviendas. A partir de varias variables, cualitativas y cuantitativas, intenta ver la relaación entre cada una de estas variables y el precio medio de la vivienda. Las variables que podemos encontrar en el dataset son estas:
1. **CRIM (Tasa de criminalidad):** Representa la tasa de criminalidad per cápita por vecindario.

2. **ZN (Proporción de tierras residenciales para lotes de más de 25,000 pies cuadrados):** Indica la proporción de terreno residencial dividido en lotes de más de 25,000 pies cuadrados.

3. **INDUS (Proporción de acres de negocios no minoristas por ciudad):** Mide la proporción de tierra utilizada para negocios no minoristas.

4. **CHAS (Variable ficticia de Charles River):** Es una variable binaria que indica si una vivienda limita con el río Charles (1 si es cierto, 0 si no).

5. **NOX (Concentración de óxidos nítricos):** Representa la concentración de óxidos nítricos (en partes por 10 millones).

6. **RM (Número medio de habitaciones por vivienda):** Indica el promedio de habitaciones por vivienda en el vecindario.

7. **AGE (Proporción de unidades ocupadas por sus propietarios construidas antes de 1940):** Mide la proporción de unidades ocupadas por sus propietarios construidas antes de 1940.

8. **DIS (Distancias ponderadas a cinco centros de empleo de Boston):** Representa distancias ponderadas a centros de empleo en Boston.

9. **RAD (Índice de accesibilidad a carreteras radiales):** Mide la accesibilidad a carreteras radiales principales.

10. **TAX (Tasa de impuesto a la propiedad de valor total por $10,000):** Indica la tasa de impuesto a la propiedad.

11. **PTRATIO (Proporción alumno-maestro):** Mide la proporción de alumnos por maestro en las escuelas del vecindario.

12. **B (1000(Bk - 0.63)^2), donde Bk es la proporción de personas de raza negra por ciudad:** Este término está relacionado con la proporción de personas de raza negra en la ciudad y se ha transformado para resaltar las áreas con alta proporción de personas de raza negra.

13. **LSTAT (Porcentaje de la población de bajos ingresos):** Representa el porcentaje de la población con bajos ingresos.

14. **MEDV (Valor medio de las viviendas ocupadas por sus propietarios en $1000):** Es la variable objetivo que queremos predecir, el valor medio de las viviendas.


## Database
El dataset que tenemos ya lo encontramos de forma tidy. Sin embargo, observamos que tiene muchos outliers. Por tanto para conseguir los valores estadísticos típicos vamos a eliminar estos outliers.


## Análisis

## Conclusión
