<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcos Gibert y Javi Torres">

<title>Practica 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="practica_3_act2_files/libs/clipboard/clipboard.min.js"></script>
<script src="practica_3_act2_files/libs/quarto-html/quarto.js"></script>
<script src="practica_3_act2_files/libs/quarto-html/popper.min.js"></script>
<script src="practica_3_act2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="practica_3_act2_files/libs/quarto-html/anchor.min.js"></script>
<link href="practica_3_act2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="practica_3_act2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="practica_3_act2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="practica_3_act2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="practica_3_act2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Practica 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcos Gibert y Javi Torres </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="presentación" class="level2">
<h2 class="anchored" data-anchor-id="presentación">Presentación</h2>
<p>El dataset Boston Housing Dataset es un conjunto de datos sobre la ciudad de Boston en relación a las viviendas. Fue realizado por el censo de 1970 y consta de 506 observaciones con 14 variables:</p>
<ol type="1">
<li><p><strong>CRIM (Tasa de criminalidad):</strong> Representa la tasa de criminalidad per cápita por vecindario.</p></li>
<li><p><strong>ZN (Proporción de tierras residenciales para lotes de más de 25,000 pies cuadrados):</strong> Indica la proporción de terreno residencial dividido en lotes de más de 25,000 pies cuadrados.</p></li>
<li><p><strong>INDUS (Proporción de acres de negocios no minoristas por ciudad):</strong> Mide la proporción de tierra utilizada para negocios no minoristas.</p></li>
<li><p><strong>CHAS (Variable ficticia de Charles River):</strong> Es una variable binaria que indica si una vivienda limita con el río Charles (1 si es cierto, 0 si no).</p></li>
<li><p><strong>NOX (Concentración de óxidos nítricos):</strong> Representa la concentración de óxidos nítricos (en partes por 10 millones). En general se suele usar esta medida para estudiar la polución del aire.</p></li>
<li><p><strong>RM (Número medio de habitaciones por vivienda):</strong> Indica el promedio de habitaciones por vivienda en el vecindario.</p></li>
<li><p><strong>AGE (Proporción de unidades ocupadas por sus propietarios construidas antes de 1940):</strong> Mide la proporción de unidades ocupadas por sus propietarios construidas antes de 1940.</p></li>
<li><p><strong>DIS (Distancias ponderadas a cinco centros de empleo de Boston):</strong> Representa distancias ponderadas a centros de empleo en Boston.</p></li>
<li><p><strong>RAD (Índice de accesibilidad a carreteras radiales):</strong> Mide la accesibilidad a carreteras radiales principales.</p></li>
<li><p><strong>TAX (Tasa de impuesto a la propiedad de valor total por $10,000):</strong> Indica la tasa de impuesto a la propiedad.</p></li>
<li><p><strong>PTRATIO (Proporción alumno-maestro):</strong> Mide la proporción de alumnos por maestro en las escuelas del vecindario.</p></li>
<li><p><strong>B (1000(Bk - 0.63)^2), donde Bk es la proporción de personas de raza negra por ciudad:</strong> Este término está relacionado con la proporción de personas de raza negra en la ciudad y se ha transformado para resaltar las áreas con alta proporción de personas de raza negra.</p></li>
<li><p><strong>LSTAT (Porcentaje de la población de bajos ingresos):</strong> Representa el porcentaje de la población con bajos ingresos.</p></li>
<li><p><strong>MEDV (Valor medio de las viviendas ocupadas por sus propietarios en $1000):</strong> Es la variable objetivo que queremos predecir, el valor medio de las viviendas.</p></li>
</ol>
<p>Todas las variables son cuantitativas excepto <strong>CHAS (Variable ficticia de Charles River)</strong> que es cualitativa nominal y <strong>RAD (Índice de accesibilidad a carreteras radiales)</strong> que es ordinal.</p>
<p>Nuestro objetivo será determinar las relaciones entre las características de un área determinada y el precio medio de la vivienda en dicha área. También nos preguntaremos que diferentes mediciones pueden estar relacionadas con la contaminación.</p>
<p>Nuestro objetivo será determinar las relaciones entre las características de un área determinada y el precio medio de la vivienda en dicha área. Además también exploraremos los efectos de la polución.</p>
</section>
<section id="database" class="level2">
<h2 class="anchored" data-anchor-id="database">Database</h2>
<p>Podemos encontrar el dataset en el paquete MASS</p>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ lubridate 1.9.2     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::select() masks MASS::select()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Veamos un resumen de los datos</p>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>      crim                zn             indus            chas        
 Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46   Min.   :0.00000  
 1st Qu.: 0.08205   1st Qu.:  0.00   1st Qu.: 5.19   1st Qu.:0.00000  
 Median : 0.25651   Median :  0.00   Median : 9.69   Median :0.00000  
 Mean   : 3.61352   Mean   : 11.36   Mean   :11.14   Mean   :0.06917  
 3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000  
 Max.   :88.97620   Max.   :100.00   Max.   :27.74   Max.   :1.00000  
      nox               rm             age              dis        
 Min.   :0.3850   Min.   :3.561   Min.   :  2.90   Min.   : 1.130  
 1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02   1st Qu.: 2.100  
 Median :0.5380   Median :6.208   Median : 77.50   Median : 3.207  
 Mean   :0.5547   Mean   :6.285   Mean   : 68.57   Mean   : 3.795  
 3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08   3rd Qu.: 5.188  
 Max.   :0.8710   Max.   :8.780   Max.   :100.00   Max.   :12.127  
      rad              tax           ptratio          black       
 Min.   : 1.000   Min.   :187.0   Min.   :12.60   Min.   :  0.32  
 1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40   1st Qu.:375.38  
 Median : 5.000   Median :330.0   Median :19.05   Median :391.44  
 Mean   : 9.549   Mean   :408.2   Mean   :18.46   Mean   :356.67  
 3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20   3rd Qu.:396.23  
 Max.   :24.000   Max.   :711.0   Max.   :22.00   Max.   :396.90  
     lstat            medv      
 Min.   : 1.73   Min.   : 5.00  
 1st Qu.: 6.95   1st Qu.:17.02  
 Median :11.36   Median :21.20  
 Mean   :12.65   Mean   :22.53  
 3rd Qu.:16.95   3rd Qu.:25.00  
 Max.   :37.97   Max.   :50.00  </code></pre>
</div>
</div>
<p>Veamos la estructura de los datos:</p>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>      crim   zn indus chas   nox    rm   age    dis rad tax ptratio  black
1  0.00632 18.0  2.31    0 0.538 6.575  65.2 4.0900   1 296    15.3 396.90
2  0.02731  0.0  7.07    0 0.469 6.421  78.9 4.9671   2 242    17.8 396.90
3  0.02729  0.0  7.07    0 0.469 7.185  61.1 4.9671   2 242    17.8 392.83
4  0.03237  0.0  2.18    0 0.458 6.998  45.8 6.0622   3 222    18.7 394.63
5  0.06905  0.0  2.18    0 0.458 7.147  54.2 6.0622   3 222    18.7 396.90
6  0.02985  0.0  2.18    0 0.458 6.430  58.7 6.0622   3 222    18.7 394.12
7  0.08829 12.5  7.87    0 0.524 6.012  66.6 5.5605   5 311    15.2 395.60
8  0.14455 12.5  7.87    0 0.524 6.172  96.1 5.9505   5 311    15.2 396.90
9  0.21124 12.5  7.87    0 0.524 5.631 100.0 6.0821   5 311    15.2 386.63
10 0.17004 12.5  7.87    0 0.524 6.004  85.9 6.5921   5 311    15.2 386.71
   lstat medv
1   4.98 24.0
2   9.14 21.6
3   4.03 34.7
4   2.94 33.4
5   5.33 36.2
6   5.21 28.7
7  12.43 22.9
8  19.15 27.1
9  29.93 16.5
10 17.10 18.9</code></pre>
</div>
</div>
<p>El dataset que tenemos ya lo encontramos de forma tidy. Sin embargo, observamos en los siguientes gráficos que tiene muchos outliers que habrá que tener en cuenta a la hora de estudiar los datos</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Cambiamos la variable chas por ‘sí’ si es un 1 y ‘no’ si es un ‘0’ para trabajar con ella de manera más cómoda.</p>
<p>Este gráfico nos muestra que la variable rad toma valores entre 1 y 24, aunque la mayoría están entre 0 y 8, a excepción de un grupo que tiene 24</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Lo podemos ver más claro en esta tabla:</p>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>  df$rad   n
1      1  20
2      2  24
3      3  38
4      4 110
5      5 115
6      6  26
7      7  17
8      8  24
9     24 132</code></pre>
</div>
</div>
<p>Para resaltar que se trata de una variable ordinal distinguiremos entre ‘bajo’ si tiene menos de 4; ‘medio’ si tiene entre 4 y 5; ‘medio alto’ si tiene más de 5 pero menos de 24 y ‘alto’ si tiene 24.</p>
</section>
<section id="análisis" class="level2">
<h2 class="anchored" data-anchor-id="análisis">Análisis</h2>
</section>
<section id="precio-medio-de-la-vivienda" class="level1">
<h1>Precio medio de la vivienda</h1>
<p>Veamos la matriz de correlaciones de las variables cuantitativas</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observamos rm (el número de habitaciones) tiene el coeficiente de correlación más alto con medv, es decir, el precio medio de la vivienda tiende a aumentar a medida que lo hace el número de habitaciones. Por otro lado, parece estar fuertemente correlacionado negativamente con medv ya que a medida que aumenta el porcentaje de. la población con bajos ingresos disminuye el precio medio de la vivienda.</p>
<p>También cabe destacar que algunas variables como el índice de criminalidad y la distancia ponderada centros de empleo no tienen tanta correlación como cabría esperar.</p>
<p>Es interesante observar que otras variables están fuertemente correlacionadas. Positivamente tenemos indus con nox (porcentaje de zona industrial con polución) y negativamente, dis con indus (distancia ponderada apuestos de empleo con porcentaje de zona industrial), dis con nox y dis con age (porcentaje de viviendas construidas antes de 1940 habitadas).</p>
<p>Veamos ahora si el hecho de bordear con el río o no tiene alguna influencia sobre el precio:</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28.44</code></pre>
</div>
</div>
<p>Vemos que en efecto el precio medio de las casas que dan al río es más alto. En particular las casas que bordean con el río tienen un precio medio de $28.44K que es aproximadamente un 26% más alto que la media.</p>
<p>Vamos a estudiar si la accesibilidad a carreteras radiales tiene alguna influencia sobre el precio:</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26.73902</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.59511</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.89254</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.40379</code></pre>
</div>
</div>
<p>Vemos que en general el precio medio de la vivienda es menor si el acceso a carreteras radiales es mayor, en particular la media de las casas con alto acceso es $16.4K, un 27% más bajo que la media. Por otro lado la media de las casas con bajo acceso es de $26.74K, un 19% por encima de la media. Es probable que esto se deba a que las casas más lujosas se encuentran en áreas más exclusivas con menos accesos y las casas más baratas están en áreas más concurridas con más accesos.</p>
<p>Veamos algunos gráficos de las variables más correlacionadas con medv:</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                rm    ptratio      lstat       medv
rm       1.0000000 -0.3555015 -0.6138083  0.6953599
ptratio -0.3555015  1.0000000  0.3740443 -0.5077867
lstat   -0.6138083  0.3740443  1.0000000 -0.7376627
medv     0.6953599 -0.5077867 -0.7376627  1.0000000</code></pre>
</div>
</div>
<p>Veamos el gráfico de medv con rm más de cerca</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Veamos el gráfico de medv con lstat más de cerca</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.24171</code></pre>
</div>
</div>
<p>En contraste con el gráfico anterior que mostraba un crecimiento aparentemente lineal del precio con respecto el número de habitaciones, parece que el decrecimiento del precio con respecto el aumento del porcentaje de pobreza es más bien logarítmico.</p>
<p>También es interesante observar que a pesar de que tanto la variable chas como la variable lstat influyen de manera notable en el precio medio de la vivienda, la media del porcentaje de pobreza en las zonas que bordean con el río es 11.24 que varía poco la media global, 12.65.</p>
</section>
<section id="contaminación" class="level1">
<h1>Contaminación</h1>
<p>Ahora vamos a ver la relación de las variables con la contaminación. En el gráfico multivariante de correlaciones hemos podido observar que nuestra variable NOX, que mide el nivel de óxidos nítricos y así nos da una idea del nivel de contaminación, está relacionada con las variables AGE, INDUS y DIS.</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En este gráfico multivariante observamos que una medida de la contaminación está positivamente correlada con la cantidad de viviendas antiguas habitadas y la proporción de tierra de negocios mayoristas. Y está negativamente correlada con la distancia a los centros de empleo. Ahora también nos podemos preguntar si las viviendas más cercanas al río tienen menor contaminación. En el sigüiente gráfico lo estudiaremos:j</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>También observaremos el cambio en relación a nuestra variable ordinal que mide la accesibilidad a carreteras radiales</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<p><img src="practica_3_act2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>En conclusión,las variables cuantitativas que más afectan al precio medio de la vivivienda son el número de habitaciones y el porcentaje de porcentaje de la población con bajos ingresos. Tiende a aumentar de manera lineal a medida que aumenta el el número de habitaciones y a disminuir de manera logarítmica a medida que aumenta la proporción de bajos ingresos.</p>
<p>Por otro lado, el hecho de bordear con el río tiende a ir asociado a un aumento del precio medio en un 26% y tener un índice alto de accesibilidad tiende a ir asociado a una disminución del precio medio en un 27%.</p>
<p>Finalmente, la polución está relacionada con la con la cantidad de viviendas antiguas habitadas, la proporción de tierra de negocios mayoristas y la distancia a los centros de empleo.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>